version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_cooperativa_socios
    restart: unless-stopped
    environment:
      POSTGRES_DB: cooperativa_socios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_socios_data:/var/lib/postgresql/data
    networks:
      - cooperativa_net

volumes:
  postgres_socios_data:

networks:
  cooperativa_net:
    driver: bridge
